### ISSUE TITLE
Controllers dont draw in Track Canvases

### ISSUE THREAD

**Issue by derselbst** [muse-sequencer/muse#460]
the control change events (mainvolume, pan, pitch) currently dont really draw, as seen here:

![musemidiwrong](https://cloud.githubusercontent.com/assets/8152480/12376855/b57a8ee4-bd08-11e5-958a-008ab6d884db.png)

however it should look like:
![musetrackcanvas](https://cloud.githubusercontent.com/assets/8152480/12376935/bd18b416-bd0b-11e5-9a54-3b9de5d875c3.png)

@terminator356 is currently looking at this, see the preface here #458

**Comment by derselbst** [comment]
Even if already 4 years past, this bug is still reproducable with recent master...

**Comment by kybos** [comment]
OK, sorry, I thought it was solved in the referenced issue.
Reopening...

**Comment by kybos** [comment]
Still can't reproduce...
![image](https://user-images.githubusercontent.com/10009541/76981440-e3daac00-693a-11ea-9c64-b84428ea3f18.png)

Can you describe exactly how to reproduce?

**Comment by derselbst** [comment]
Argh, my fault. I was missing a call to `ldconfig` after make install. Works fine, pls. apologize.

(Didn't notice I still had revision 538467edd047fcdb355f9bc911f0c7cee1386ad3 installed, where it was still broken.)

Sorry again. And thanks for the fix!
