### ISSUE TITLE
Muse crashes when project is loaded that contains a Carla synth (acting as a VST plugin to Muse) loaded with a Win32 VST

### ISSUE THREAD

**Issue by zorro2055** [muse-sequencer/muse#964]
Hello, not sure if this is a problem with Muse or Carla, but I thought I would try here first because Carla worked correctly with Ardour for this particular issue.

I can add Carla as a synth, then choose NeoOrchestra as the Win32 VST that Carla is running.  The synth works normally if I attach a MIDI track to it.  However, if I save the project, close Muse, open Muse, and load the project, Muse crashes after loading the project.  If Carla is not running a plugin or the one non Win32 VST that I tried, Muse does not crash upon loading the project.

For a comparison, I did try this with Ardour and it works fine.  There are no crashing issues.  I was able add a Carla synth to Ardour with Carla using the NeoOrchestra Win32 VST, save the project, close Ardour, open Ardour and load the project without Ardour crashing.

I am running Muse 4.0pre2.

Running Muse at the command line and trying to load the Project that causes the crash, these messages are outputted:
Setting project path to /home/johnd/Documents/DragonDefenseMuse/IntroductionUntilGameplay
Carla-Rack-0: loading chunk from sysex!
INFO: Requested timer frequency:1024 actual:1000
Using WINEPREFIX '/home/johnd/.wine', with base RT prio 15 and server RT prio 10
Starting plugin bridge, command is:
/usr/lib/vst/carla.vst/carla-bridge-win32.exe "VST2" "/home/johnd/.wine/drive_c/Program Files/Vstplugins/NeoOrchestra/NeoOrchestra.dll" """" 1313821251
CarlaThread setup with realtime priority successful
Carla Bridge Ready!
Segmentation fault

Attached is the .med file (compressed in a zip file so github will let me attach it) that I am trying to open.  Let me know if additional info is needed.  I compiled Muse from source, so I'm willing to try a patch, etc if needed.

Thanks!

[IntroductionUntilGameplay.zip](https://github.com/muse-sequencer/muse/files/5963353/IntroductionUntilGameplay.zip)

**Comment by zorro2055** [comment]
And I'm running the latest Carla version 2.2.0.

**Comment by zorro2055** [comment]
Hmmm, I thought I had updated to 4.0pre2, but it looks like I still am running 4.0pre1.  Let me check that and update this issue accordingly.

**Comment by zorro2055** [comment]
Okay, I just tried with Muse 4.0pre2.  Still the same issue.

**Comment by kybos** [comment]
Two things you can try:
1. Carla plugin is available in LV2 and VST version. Try the other one.
2. Run muse4 with the -D switch to get more debug info.

**Comment by zorro2055** [comment]
Thanks for the response.  So I was using Carla as a VST plugin and have attached the entire log with the -D option from launching Muse to opening the .med file that had Carla as a VST plugin with NeoOrchestra Win32 VST loaded in Carla to the crash.

Then, I tried using Carla as an LV2 plugin with NeoOrchestra Win32 VST loaded in Carla.  When I opened the .med file that had this synth saved, Muse did NOT crash.  So that is good.  I am also attaching a log file where I launch Muse and load this saved .med file.

I also checked Ardour which only appears to support VST plugins unless I am missing something.

So, I can go ahead and use Carla as an LV2 plugin since that works fine.

If you would like to get to the bottom of why Carla as a VST plugin is causing an issue when loaded with a Win32 VST, I can run any other tests that you think might be useful or try any patches that might help.
[CarlaAsVSTPluginCrashLog.txt](https://github.com/muse-sequencer/muse/files/5969617/CarlaAsVSTPluginCrashLog.txt)
[CarlaAsLV2PluginLog.txt](https://github.com/muse-sequencer/muse/files/5969618/CarlaAsLV2PluginLog.txt)

**Comment by kybos** [comment]
@spamatica @terminator356 

Could you have a look at the logs? I am not familiar with this part of the code.
There are many suspicious Carla LV2 (!) errors when the Carla VST (!) plugin is used. When Carla LV2 is used, I see none of the errors. Doesn't seem to make any sense.

**Comment by zorro2055** [comment]
If it helps, here is also a log where I add in Carla as a VST plugin to Muse, than load the NeoOrchestra Win32 VST plugin into Carla, choose the specific instrument and play a single note in the Win32 plug GUI.  Doing this does not cause a crash.  Only if I saved, then loaded the saved file would it crash.
[AddingCarlaAsVSTPluginLog.txt](https://github.com/muse-sequencer/muse/files/5972317/AddingCarlaAsVSTPluginLog.txt)

**Comment by spamatica** [comment]
Regarding the logs, it is curious, are there multiple versions of Carla on the system? The LV2 ttl errors I believe are printed during startup when the plugin is discovered and should thus be printed regardless of which plugin is used.

As for the crashing. Loading win32 VSTs can be unstable business. I'm not all that familiar with Carla and this far I've been unable to load a win32 vst. I think I've done it before, somehow... 
Is this NeoOrchestra vst is available anywhere for testing?

Another possibility is that this is related to a crash bug in pre2 which happens when a midi editor has been opened and closed. Don't think it is what happens here but thought I would mention it. In current master it is fixed.

**Comment by terminator356** [comment]
Looked at the first log. All seems normal until the seg fault. Sadly, no useful info there.

I actually ran Carla a few times some months ago. It seemed to work OK with MusE,
 but there was no VST support compiled into my package, so I passed on that experiment.

I see he has dssi-vst in there. Recall that I recently succeeded in compiling and running dssi-vst,
 without the continuous errors that plagued earlier versions. That was amazing. Recent kernels fixed it, I think.
Funny he gets this redundant identical path warning:
"Ignoring DSSI synth label:NeoOrchestra.dll uri: path:/usr/lib/dssi/dssi-vst.so duplicate of path:/usr/lib/dssi/dssi-vst.so"
Not sure what's up with that. It's supposed to warn about **different** paths pointing to the same plugin, not paths
 that are the same.
My first impression is that MusE paths in Global Setting may overlap, or it is complaining about the same plugin being
 reported by both dssi-vst AND Carla, some overlapping going on. Some path settings experimentation may be required.
Maybe that's where the crash is happening. Like MusE thinks it should load the particular plugin via dssi-vst 
 when really it should have loaded it via Carla, or vice-versa. ie. confusion about how exactly to load the plugin,
 which bridge to use, getting mixed up picking the wrong bridge.

About the LV2 errors: It's complaining that all (most?) of his Carla LV2 plugins are not directories, 
 each LV2 plugin should be in its own directory. But... these are specifically Carla LV2 bridges and plugins and so on,
 not regular LV2 plugins. So LV2 probably doesn't like that. Possibly he'd get the same errors with a different DAW -
 unless possibly MusE LV2 paths are not correct in Global Settings?

About the "Jack calling when audio disconnected": Yeah that's normal. We spit out continuous warning errors
 (really it is just informational) each audio cycle while the system waits for Jack to be up and running. No worries there.

About the many "device not found": Yeah that's normal too. It just means there was no MusE midi device
 in that MusE midi port slot. Again, more informational than error.

**Comment by zorro2055** [comment]
Ah, a lot of info there, but here is some feedback off the bat.
1.  Unfortunately, NeoOrchestra.dll is a paid plugin.  It runs different instruments.  I am running the Guqin.  Link if for some reason you did want to buy it:  https://neovst.com/product/guqin/
2. I uninstalled DSSI-VST since I don't really use it anyway.  Muse still crashes when loading .med with Carla running NeoOrchestra.dll (Win32 VST).  See attached log.
[CarlaAsVSTPluginDssi-VstRemovedCrashLog.txt](https://github.com/muse-sequencer/muse/files/5975028/CarlaAsVSTPluginDssi-VstRemovedCrashLog.txt)
3.  I tried loading in what I believe is a Win64 (Qin_RV_x64.dll) into Carla.  When I save that, exit Muse, launch Muse and open the file, Muse does NOT crash.  Log file attached.
[CarlaAsVSTPluginWithWin64Dssi-VstRemovedCrashLog.txt](https://github.com/muse-sequencer/muse/files/5975030/CarlaAsVSTPluginWithWin64Dssi-VstRemovedCrashLog.txt)
4.  Just restating from before that when Muse tries to open a saved file with Carla as VST loaded with NeoOrchestra.dll, it crashes.  If I do the same thing with Ardour, Ardour does NOT crash when it opens the saved file.
5. Other than opening a saved file with Carla as VST running NeoOrchestra.dll crashing Muse, NeoOrchestra.dll appears to run well so far.  I have not seen any other crashes... at least yet.

I'll try to read those comments more a little later to see what else I can test...

**Comment by kybos** [comment]
Please look at this section in the wiki:

https://github.com/muse-sequencer/muse/wiki/Helping#report-bugs

If you could provide a gdb backtrace, perhaps it would give a hint about the cause.

**Comment by zorro2055** [comment]
Ok, I followed the instructions from the report bugs section.  Attached is the full backtrace from that:
[LoadingSavedFileCarlaAsVstPluginWithNeoOrchestraLoadedFULLBACKTRACE.txt](https://github.com/muse-sequencer/muse/files/5976062/LoadingSavedFileCarlaAsVstPluginWithNeoOrchestraLoadedFULLBACKTRACE.txt)

Then just as reference if it is useful, I attached a screenshot with the Muse, Carla, and NeoOrchestra partial windows visible.
![MuseCarlaNeoOrchestra](https://user-images.githubusercontent.com/5027366/107855794-165e8480-6dea-11eb-8fe5-80132b8b5f47.png)

And just FYI, to get the Win32 VST support in Carla, I had to compile separate modules in Carla, then active experimental features in Carla to get it to work.  I had to install cross compilers to do this step.  Plus Wine had to be installed of course.  Here is a stippet from Carla's INSTALL.md file about that.  Also, I think there might be binaries available for this for Ubuntu (which I do not run).  I might be remembering that incorrectly though.

_### Windows plugins (via Wine)

Requires a mingw compiler, and winegcc.

First, we build the Windows bridges using mingw, like this: (adjust as needed)
```
make win32 CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-g++
make win64 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++
```

To finalize, we build the wine<->native bridges using winegcc:
```
make wine32
make wine64_

**Comment by zorro2055** [comment]
And these lines were right before the full backtrace:

Thread 9 "muse4" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe831e640 (LWP 8583)]
0x00007fffe0f7281d in ?? () from /usr/lib/vst/carla.vst/CarlaRack.so
(gdb) bt full

**Comment by spamatica** [comment]
Alright, glad you managed to make a backtrace (I sneakily added a few words about having to restart the debug session with 'continue' just a few hours ago, not sure it was necessary).

Unfortunately the backtrace indicates that the crash occurs within CarlaRack. It is not ruled out that MusE is responsible for causing the error but since it crashes in Carla the odds are against us that we can find the cause.

If you want to continue your crusade to find the problem (it could be a learning experience :) ) I think you need to recompile Carla with debug enabled and redo this test.

**Comment by zorro2055** [comment]
Ah, ok, I'll give that a try to recompile Carla with debugging and post the full backtrace here when I am hopefully successful!

Yeah, I did have to use 'continue' in the debug session.  Using the gdb help allowed me to figure that out once I noticed that Muse had paused.

**Comment by terminator356** [comment]
Thank you very much for the backtrace. Good stuff.

A quick suggestion to try to nail down the cause:
Try the very same experiment with different brands of VST synthesizers, through Carla.
Try simpler more basic synthesizers, as well as big and complex synthesizers comparable to Neo.
In other words, simply replace Neo with other synths and do the exact same tests, saving and re-loading.
If any of them crash, post the med file, and the backtrace if you can. Many Linux VST synths save and load fine with MusE.


Long explanation of what's going on:
VST plugins have the ability to allow the host to save and restore the complete **state** of the synth.
This state is in the form of a System Exclusive midi event, and we store the event in our .med song files.
In your zipped .med song file, this event is 1079639 bytes long and begins at line 1065 and ends at line 68546.
When this song loads, in the backtrace at number 7 and 6 you can see MusE dispatching this event to the synthesizer,
 in this case Carla-Rack, to restore the complete state of the synthesizer when the song was last saved.
You can see the header as "|\tVSTSAVE" which is correct. The data following the header is likely correct as well.

Side note:
Interesting. Many synths save their complete state as incomprehensible raw binary sysex data.
I decoded the first few dozen bytes of this sysex data in your song. And the last few, as a check.
Tada! All of it is XML text!
Thus, I am guessing that this is Carla's XML data, not the synth's raw data, and perhaps Carla
 encapsulates the synth's raw data within Carla's XML text. But I'm not sure. The data was hand-decoded,
 and there's a million more bytes in there to decode...

Possible causes of the crash when loading:
1) MusE is sending this initialization event too soon. The synthesizer has not fully constructed or loaded yet.
Mm, possibly. I recall trouble with ordering, maybe it was LV2. But, other Linux VST synths work just fine.
2) MusE is improperly sending this initialization event. Wrongly formatted? Wrong functions calls or sequences?
But, other Linux VST synths work just fine.
3) The 1 million byte sysex is too big? Should we chunk it? Don't think so. Tested large sysex before. Shhhhould be OK.
But that's a big sysex. MusE memory (de-)allocation errors? Our EvData class was tricky. Bugs?
4) The synthesizer is mishandling the sysex. Ain't our fault. Test another synth brand.
5) Carla is mishandling the sysex. Ditto.

**Comment by spamatica** [comment]
> MusE is sending this initialization event too soon. The synthesizer has not fully constructed or loaded yet.
Mm, possibly. I recall trouble with ordering, maybe it was LV2. But, other Linux VST synths work just fine.

This one could hold some merit. I use Addictive Drums 2 win32 VST through AirWave all the time and it is not able to recall it's settings, it does not crash though. 
I did look at this a long time ago but didn't get anywhere, but I didn't think about timing.. Addicitve Drums 2 is notorious for taking an enormous time to instantiate through Wine so timing problems is definitely not out of the question.
...though my understanding of VST may be too limited. I can try to have another look though.

Meanwhile, looking forward to see if you manage to get a backtrace with debug built Carla @zorro2055, it should be able to get us further.

**Comment by terminator356** [comment]
@spamatica Could you run a few tests with AD and AW? Do just like the OP, save a song and examine (post)
 the med file to see if at least we were able to store the synth's state sysex in the song.
Maybe there's nothing stored there at all? Meaning AW does not handle saving/restoring VST states?

**Comment by zorro2055** [comment]
@spamatica  Okay, I was able to compile Carla with debugging symbols and get a full backtrack from that!  Attached below:
[LoadingSavedFileCarlaAsVstPluginWithNeoOrchestraLoadedFULLBACKTRACEWithCarlaDebugAlso.txt](https://github.com/muse-sequencer/muse/files/5976683/LoadingSavedFileCarlaAsVstPluginWithNeoOrchestraLoadedFULLBACKTRACEWithCarlaDebugAlso.txt)

@terminator356 So far I have tried one other Win64 (I believe) VST loaded in Carla called Qin_RV_x64.dll which worked fine when loading from a saved file.  I also tried a piano plugin (LV2 though) into Carla.  That worked fine as well.  I don't have any other Windows VSTs, but I could try some of the other linux VSTs I have if y'all think that is a good idea after reviewing the latest full backtrace file.

**Comment by terminator356** [comment]
Awesome, thanks!

Yes indeed, Carla embeds each synth's state into its XML sysex event block, as a base64 encoded string.
It's the part of the sysex event where you see reeeeally long strings of '41' ASCII A, usually a good sign that it's base64.

Let me say that this screams as an opportunity for MusE to compress our sysex data with qCompress,
 just like we do with our LV2 state data. Sorry about that 3.8MB song file size! An oversight. Our sysex writing
 routines have a TODO beside the code where we could compress. Should have been done some years ago.

At the top of the backtrace we see where Carla is setting up a string to hold this 1MB base64 encoded string,
 and appending some text to it: `CarlaString::operator+=` and `CarlaString::asBase64`

But ouch. We see this: `value requires 4702111234474983746 bytes, which is more than max-value-size`
and then later (above): `value requires 458725 bytes, which is more than max-value-size`
Strange. it says `dataSize=801792` which seems reasonable given the sysex is 1MB.
Why is the value's data required size so truly ridiculous high above?

It's possible to say this is Carla's fault. Something is wrong in there. Not enough memory, or wrongly calculated.

But you say this seems to work fine in Ardour? If I assume Ardour chunks its sysex when sending to a synth
 then I must say it sure does _start to look like_ the answer to this question might be **yes**:
> 3) The 1 million byte sysex is too big? Should we chunk it?

I already made some **special classes** to handle sysex chunking much more easily.
The only place I use them so far is our ALSA midi devices, when sending and receiving large sysex.

Maybe it's time to add this chunking to both our Jack midi devices and our synthesizer devices.

But what worries me is how do we know if a synth can handle chunked sysex in the first place?
Some might not. Some might actually work better just sending the complete long sysex instead.
Hey look at us for example, I only handle chunking in ALSA midi !

**Comment by zorro2055** [comment]
Very interesting.  Yes, Ardour does not crash when it opens a save file with Carla As Vst Plugin with NeoOrchestra.dll loaded.  So something is different...

Not sure if this helps, but attached is the Ardour save file with Carla As Vst Plugin with NeoOrchestra.dll loaded.  Maybe that will shed some insight into what Ardour might be doing?
[test_neoorchestra.zip](https://github.com/muse-sequencer/muse/files/5977113/test_neoorchestra.zip)

**Comment by terminator356** [comment]
And yet, this is puzzling, why no crash with LV2? It's the same long sysex data:
> Then, I tried using Carla as an LV2 plugin with NeoOrchestra Win32 VST loaded in Carla. When I opened the .med file that had this synth saved, Muse did NOT crash. So that is good.

Something wrong with Carla's VST code?
Something wrong with our sysex data? Hmm...

**Comment by zorro2055** [comment]
Was just looking closer at the full backtrace with Carla debug info.  I have no idea if this is relevant, but there are multiple Python Exceptions for really large values.  Is that useful?  Here are the line numbers in that file and the error:

Line 22
Python Exception <class 'gdb.error'> value requires 4702111234474983746 bytes, which is more than max-value-size:
Line 111
Python Exception <class 'gdb.error'> value requires 2893606913523066944 bytes, which is more than max-value-size:
Line 125
Python Exception <class 'gdb.error'> value requires 723401728380766736 bytes, which is more than max-value-size:
Line 142
Python Exception <class 'gdb.error'> value requires 723401728380766736 bytes, which is more than max-value-size:
Line 152
Python Exception <class 'gdb.error'> value requires 723401728380766736 bytes, which is more than max-value-size:

I have no idea if that is normal or not, but thought I would point it out.

**Comment by kybos** [comment]
> Not sure if this helps, but attached is the Ardour save file with Carla As Vst Plugin with NeoOrchestra.dll loaded. Maybe that will shed some insight into what Ardour might be doing?
> [test_neoorchestra.zip](https://github.com/muse-sequencer/muse/files/5977113/test_neoorchestra.zip)

It seems that Ardour doesn't save Carla state (or maybe there is some other mechanism...). That could explain why it doesn't crash.
@zorro2055 Does Ardour keep your settings when you change something in your Neo plugin?

**Comment by terminator356** [comment]
> It seems that Ardour doesn't save Carla state

Yes, there is a compressed base64 block for the Carla 'processor' in his file beginning at around line 330.

> Python Exception <class 'gdb.error'> 

Actually, I'm thinking it seems that these may simply be gdb errors, unable to represent some variable data.
But still weird.

**Comment by zorro2055** [comment]
@kybos Good question.

Short answer:  After checking, yes, the NeoOrchestra settings appear to be saved.  And only 4 bytes changed in the chunk program section (line 331) of the save file where I suspect this change was saved.  Vim does not show the whole length of this chunk program line, but I think it is gigantic.

Long answer with lots of details:
First, I changed this specific setting and saved to a different file(knob circled in red):
![ChangedNeoOrchestraSetting](https://user-images.githubusercontent.com/5027366/107882696-820b2500-6eb0-11eb-9cff-25afd2f50913.png)
After I checked that the NeoOrchestra setting change was saved, I went to compare the two save file, one before my change and one after my change.  Diff did not show any change in the chunk program line probably because it was too big I am guessing.  Here is what diff showed the difference was for reference:
-  <LastUsedSnapshot name="test_neoorchestra"/>
+  <LastUsedSnapshot name="test_neoorchestra_2"/>
This is due to the fact I gave both saved files different names.
So I found vbindiff and used that.  First I searched for chunk so it would align both files at that point.
![ChunkLineAligned](https://user-images.githubusercontent.com/5027366/107883099-6dc82780-6eb2-11eb-8bad-2c5267b6b684.png)
Then I hit return to see the first difference and got this (differences in red):
![ChunkLineDifferences](https://user-images.githubusercontent.com/5027366/107883136-b1229600-6eb2-11eb-8aa3-a3b03118bed1.png)
When I hit return again, the next difference was past the chunk.
Here is one zip file with both of these files which are actually two project directories.  The only difference between the two is the single setting change that I made in NeoOrchestra.  Note that there is one other file in that project that I did not attach before called instant.xml.  That seems to most likely just save the windows positions I think though and shows no difference between the two projects.  In these Ardour projects, I have the main, preference, and virtual midi keyboard windows open.  Also, there are a bunch of empty directories in the project folder.
[test_neoorchestra_projects.zip](https://github.com/muse-sequencer/muse/files/5978117/test_neoorchestra_projects.zip)

Lastly, on a semi side note, I thought that Ardour only supported VST plugins, however, it looks like it supports LV2 plugins as well.  After looking at the save file though, it lists CarlaRack as a vst plugin.  And when I search the file for LV2, nothing pops up.  So I still believe Ardour is loading Carla as a VST plugin.  See below for screenshots, etc showing this.

Screenshot of three windows I have open.  VST (circled in blue) is below plugins which is why I thought just VST files were supported.  But when plugins is highlighted, there is a line talking about LV2 (circled in red), so I assume LV2 is also supported.
![ArdourWindows](https://user-images.githubusercontent.com/5027366/107883987-eaa9d000-6eb7-11eb-967a-9aedd9d9f289.png)

But line 206 in .ardour save file says:
      <Processor id="234" name="Carla-Rack" active="1" user-latency="0" use-user-latency="0" type="lxvst" unique-id="1131572323" count="1" custom="0"

Notice type="lxvst", so I still think CarlaRack is loaded as a VST plugin.

And I think that is it.  Let me know what y'all think.  :)

**Comment by zorro2055** [comment]
@terminator356 Due to those potential GDB errors, if you think it is a good idea for me to step through this opening file sequence to try and track variable sizes, etc, let me know.  I went through a basic gdb tutorial a while ago though, so some fast tips on where (and how) to put a breakpoint(s), what variable (and how) to check for it would be appreciated.  I could probably fill in the blanks.

**Comment by terminator356** [comment]
From CarlaString.hpp:
`static CarlaString asBase64(const void* const data, const std::size_t dataSize)`
`const std::size_t kTmpBufSize = std::min(carla_nextPowerOf2(static_cast<uint32_t>(dataSize/3)), 65536U);`
`char strBuf[kTmpBufSize+1];`
`       for (std::size_t s=0; s<dataSize; ++s) `
`           ret += strBuf;`

From the backtrace:
`s = 344042`
`kTmpBufSize = 65536`

And again from CarlaString.hpp:
`CarlaString& operator+=(const char* const strBuf) noexcept`
`        const std::size_t newBufSize = fBufferLen + std::strlen(strBuf) + 1;`
`        char              newBuf[newBufSize];`
`        std::strcpy(newBuf, fBuffer);`   <<<<<<<<<<<<<< The offending line 775 where it crashes
`        std::strcat(newBuf, strBuf);`

You can see from `kTmpBufSize = 65536` that it is using 64KB of stack space for each sub-string.
You can see from `s = 344042` that it has already processed 344041 characters and is about to process
 some more at the 344042th character.
Hm, using 65KB of stack space for each sub-string? Stack overflow?
It seems Carla is choking on the string.
Possibly by sheer coincidence it is running out of stack space when run with MusE and not Ardour?

**Comment by terminator356** [comment]
Actually it's worse than I indicated:
`CarlaString& operator+=(const char* const strBuf) noexcept`
`const std::size_t newBufSize = fBufferLen + std::strlen(strBuf) + 1;`
`char newBuf[newBufSize];`
`std::strcpy(newBuf, fBuffer); <<<<<<<<<<<<<< The offending line 775 where it crashes`
`std::strcat(newBuf, strBuf);`

The newBufSize is the **current size** **plus** the incoming sub-string size of 64KB.
So the newBuf array is actually hundreds of thousands of bytes long, and created on the stack !!!
I'd say looks like a stack overflow. And a coincidence that it happens in MusE but not Ardour.

Time to ask FalkTX (the author) to chime in on this, ask if we should be chunking the sysex data.
Will Carla accept chunked sysex data? Will the synths?

**Comment by terminator356** [comment]
Posted an issue at Carla's github site. May take some time, he's probably quite busy...

**Comment by zorro2055** [comment]
Ah, great, thanks.  Okay, so I'll hold off on doing any stepping through the code unless you think that would still be a good thing to do right now.

**Comment by terminator356** [comment]
Got an answer.
>This is without a doubt a Carla bug.
Constructing variables on the stack based on external input is dangerous.
I will see if I can reproduce the bug, so I can confirm when doing a fix.

Woohoo! We'll see what shakes out. Follow the issue there if you'd like.

**Comment by zorro2055** [comment]
Sounds good!  Will definitely follow the issue there as well.

**Comment by zorro2055** [comment]
As you probably saw on the Carla bug, falkTX's patch fixed the problem!  Thanks all for guiding me through this!

As mentioned on the other thread, I am also attaching a zip file here with the save file I used.  The debug log showing what happened when I opened Muse, loaded the saved file, then closed Muse after the file was loaded is also in there.
[SuccessfulLoadingMuseSaveFileWithCarlaAsVSTPluginWithNeoOrchestraLoadedLogAndSaveFile.zip](https://github.com/muse-sequencer/muse/files/5979680/SuccessfulLoadingMuseSaveFileWithCarlaAsVSTPluginWithNeoOrchestraLoadedLogAndSaveFile.zip)

If any other info is needed from me, just let me know.

**Comment by zorro2055** [comment]
Also, I checked if the save file with this same updated Carla as VST plugin with NeoOrchestra loaded still worked with Ardour.  And it does, so that is good as well.

**Comment by kybos** [comment]
Including a link to the Carla issue for reference here:

https://github.com/falkTX/Carla/issues/1355

@terminator356 
> > It seems that Ardour doesn't save Carla state
> 
> Yes, there is a compressed base64 block for the Carla 'processor' in his file beginning at around line 330.

Your are of course right. That was my stupid mistake, because I was looking for that huge chunk but my text editor was displaying it in one single line, so I missed it.

@zorro2055 
I understand everything is working now, so we can close this ticket?
Thanks for your time and all the work on this difficult bug, much appreciated.

**Comment by terminator356** [comment]
Love it! I just love getting stuff done like this! Especially incidental stuff that takes us out of our comfort zone.
The fix applies to such a general part of the software. It should help with all aspects, including the LV2 version and so on.

I'll see if I can do that compression thing. Will greatly reduce your file sizes. Can't promise soon, very busy. Stay tuned...

Let us know if any more trouble.
Enjoy the beautiful plugin.
Tim.

**Comment by zorro2055** [comment]
@kybos Yeah, everything is working now.  Thanks for checking.

@terminator356 Yes, very cool!  It seemed to go pretty smoothly for what it was?  I kind of hope I run into another bug, but not too soon, to do this again.  :D  Anyway, thanks again.

Compression would be great, but only when time allows of course.

**Comment by terminator356** [comment]
- LinuxVST synths: Replaced songfile midistate with customData state block.
      Uses compressed base64 just like several of our other areas.
      Old songs with midistate still load and are converted upon saving.

Compression done! In git master now.
While we have your attention could you give it a whirl?
Existing song files are still supported. **They will be converted upon saving.**

Open an existing Neo-(or other LinuxVST-)based big song file (which has the old 'midistate') and **re-save it**.
New file size should be smaller because any LinuxVST's midistate is replaced with a compressed base64 customData.
Let me know if things work OK.
And out of curiosity the savings in file sizes.

Tested OK here with existing songs containing UHe LinuxVST plugins, both in the rack and as synthesizer tracks.

**Comment by zorro2055** [comment]
Very nice!  I'll definitely try this out and let you know the file size difference and if there are any issues.  I have one other Win64 VST that seems complicated, so might generate a fairly large save file as well.  I'll probably try a LinuxVST although I'll have to pull that from the internet.  I'll do this Tuesday (today now) night.

**Comment by zorro2055** [comment]
Ok, I ran the tests.  First, here is an ls -l of the files.  I did a Save As to save the after Compression files and still have the uncompressed files.

> johnd@thor ~/Documents/DragonDefenseMuse $ ls -l *Compression*
> -rw-r--r-- 1 johnd weston-launch   75186 Feb 16 22:35 CarlaWithNeoOrchestra_afterCompression.med
> -rw-r--r-- 1 johnd weston-launch 4021726 Feb 16 21:38 CarlaWithNeoOrchestra_beforeCompression.med
> -rw-r--r-- 1 johnd weston-launch   50741 Feb 16 22:36 CarlaWithQin_RV_afterCompression.med
> -rw-r--r-- 1 johnd weston-launch   69842 Feb 16 21:43 CarlaWithQin_RV_beforeCompression.med
> -rw-r--r-- 1 johnd weston-launch   38626 Feb 16 22:34 SpectMorph_afterCompression.med
> -rw-r--r-- 1 johnd weston-launch   30789 Feb 16 22:31 SpectMorph_beforeCompression.med
> -rw-r--r-- 1 johnd weston-launch   43061 Feb 16 22:33 amsynth_afterCompression.med
> -rw-r--r-- 1 johnd weston-launch   38345 Feb 16 21:36 amsynth_beforeCompression.med

It turns out only Neo (Win32 VST) is really large, but that saw great improvement.  Qin_RV is a Win64 (I believe) VST.  I though Qin_RV would be create a pretty big uncompress file, but it did not.  amSynth is a Linux VST.  SpectMorph is a Linux VST.

File                                     Original Uncompressed Size               Compressed Size          % Smaller
CarlaWithNeoOrchestra     4.02 MB                                               75.2 kB                         98.1
CarlaWithQinRV                 69.8 kB                                                50.7 kB                         27.4
SpectMorph                        30.8 kB                                                38.6 kB                        -25.3
amSynth                             38.3 kB                                                43.1 kB                        -12.5

So Carla with Neo has a huge decrease in size from 4.02 MB to 75.2 kB.  It looks like somewhere between a uncompressed file size of 69.8 kB and 38.3 kB, compression will increase the file size, but not very much.  The small file size increase of smaller files does not bother me especially since the file size decrease with the Neo plugin is amazing, but obviously, it is up to y'all if that is acceptable or not.

Also, all plugins still worked after loading the compressed save file.  Except I could not verify if SpectMorph played sound as I had just downloaded that and do not have it configured quite right yet.

Attached are the compressed and uncompressed save files in a zip file for reference.  Let me know if you need other info.
[MuseCompressedAndUncompressedSaveFiles.zip](https://github.com/muse-sequencer/muse/files/5993354/MuseCompressedAndUncompressedSaveFiles.zip)

**Comment by zorro2055** [comment]
I was just thinking, maybe while saving, Muse could check if compress or uncompressed is smaller, then save in whichever one is smaller and maybe have a text note saying that data is compressed or uncompressed?

**Comment by spamatica** [comment]
Hi again, thanks for going the extra mile and testing :) 

I think it will be up to Tim if he wants to work more on this. I didn't check the zip file for the truth but judging by the numbers you mention I don't think it's really worth it to check if it is better to save uncompressed. The data is still not human readable and the size difference is quite small.

**Comment by zorro2055** [comment]
Sounds good to me.  Its definitely great to have that compression feature in now.  Thanks for that and Muse of course!

**Comment by terminator356** [comment]
Hi. I looked at the files.
Nothing to worry about. It's nothing to do with the compression.
In the 'after' files, somehow you managed to set all of the MidiPort instruments to Generic midi.
Not sure how you managed to do that, they are usually set to 'GM' by default, and we don't bother
 including the line in the med file when it is on default 'GM'.
Since there are 200 midi ports, this adds 200 extra lines to the med file.
      <midiport idx="0">
        <defaultInChans>1</defaultInChans>
        <instrument>Generic midi</instrument>    <<<<<  Extra line.
        <name>Midi Through Port-0</name>
        </midiport>

I think you can set all the ports back to 'GM' or another desired instrument 'wholesale' in the 
 midi ports/devices dialog in the ports list, by holding a key down while selecting a single port's instrument,
 and it will affect all the ports in the list. I think. Maybe not... Don't quote me on that...

**Comment by zorro2055** [comment]
Ah, my bad.  I figured out what was going on.  When I compiled the Muse from the master branch, I did not install it in a local directory.  I just ran it directly from the directory it was compiled in.  Muse said something about not finding a template and was a different color, but I figured that was just because that was development in process.  Anyway, when I did the make install to install to a local directory, then ran muse4 at from that location, that did NOT add those extra 200 midi ports when I saved.

So, updated ls -l gives:
```
johnd@thor ~/Documents/DragonDefenseMuse $ ls *before* *afterCompression2* -l
-rw-r--r-- 1 johnd weston-launch   66140 Feb 19 23:04 CarlaWithNeoOrchestra_afterCompression2.med
-rw-r--r-- 1 johnd weston-launch 4021726 Feb 16 21:38 CarlaWithNeoOrchestra_beforeCompression.med
-rw-r--r-- 1 johnd weston-launch   41695 Feb 19 23:05 CarlaWithQin_RV_afterCompression2.med
-rw-r--r-- 1 johnd weston-launch   69842 Feb 16 21:43 CarlaWithQin_RV_beforeCompression.med
-rw-r--r-- 1 johnd weston-launch   29580 Feb 19 23:06 SpectMorph_afterCompression2.med
-rw-r--r-- 1 johnd weston-launch   30789 Feb 16 22:31 SpectMorph_beforeCompression.med
-rw-r--r-- 1 johnd weston-launch   34015 Feb 19 22:41 amsynth_afterCompression2.med
-rw-r--r-- 1 johnd weston-launch   38345 Feb 16 21:36 amsynth_beforeCompression.med
```

So then updated stats are:
```
File                      Original Uncompressed Size    Compressed Size    % Smaller
CarlaWithNeoOrchestra     4.02 MB                       66.1 kB            98.4
CarlaWithQinRV            69.8 kB                       41.7 kB            40.3
SpectMorph                30.8 kB                       29.6 kB            3.90
amSynth                   38.3 kB                       34.0 kB            11.2
```

So everything looks good, all the files end up smaller!

Files are attached for reference:
[MuseCompressedAndUncompressedSaveFilesTake2.zip](https://github.com/muse-sequencer/muse/files/6014249/MuseCompressedAndUncompressedSaveFilesTake2.zip)

And here is a diff -u between amSynth saved file before and after compression for reference:
```
--- amsynth_beforeCompression.med       2021-02-16 21:36:31.369392678 -0600
+++ amsynth_afterCompression2.med       2021-02-19 22:41:13.731044739 -0600
@@ -19,7 +19,7 @@
     <extSync>0</extSync>
     <bigtimeVisible>0</bigtimeVisible>
     <transportVisible>0</transportVisible>
-    <geometryMain x="184" y="289" w="1728" h="733"></geometryMain>
+    <geometryMain x="28" y="280" w="1728" h="733"></geometryMain>
     <geometryTransport x="0" y="0" w="100" h="30"></geometryTransport>
     <markerVisible>0</markerVisible>
     <mixer1Visible>0</mixer1Visible>
@@ -109,6 +109,10 @@
         <openFlags>0</openFlags>
         </mididevice>
       <mididevice>
+        <name>MusE Port 0</name>
+        <openFlags>3</openFlags>
+        </mididevice>
+      <mididevice>
         <name>jack-midi-0</name>
         <type>1</type>
         <openFlags>3</openFlags>
@@ -953,95 +957,12 @@
       <port>2</port>
       <guiVisible>0</guiVisible>
       <nativeGuiVisible>0</nativeGuiVisible>
-      <midistate version="2">
-        <event type="2" datalen="1348">
-          7c 09 56 53 54 53 41 56 45 00 61 6d 53 79 6e 74 
-          68 31 2e 30 70 72 65 73 65 74 0a 3c 70 72 65 73 
-          65 74 3e 20 3c 6e 61 6d 65 3e 20 44 65 72 72 65 
-          6e 20 31 0a 3c 70 61 72 61 6d 65 74 65 72 3e 20 
-          61 6d 70 5f 61 74 74 61 63 6b 20 30 2e 31 35 0a 
-          3c 70 61 72 61 6d 65 74 65 72 3e 20 61 6d 70 5f 
-          64 65 63 61 79 20 30 2e 37 34 30 30 39 0a 3c 70 
-          61 72 61 6d 65 74 65 72 3e 20 61 6d 70 5f 73 75 
-          73 74 61 69 6e 20 30 2e 32 31 31 32 32 32 0a 3c 
-          70 61 72 61 6d 65 74 65 72 3e 20 61 6d 70 5f 72 
-          65 6c 65 61 73 65 20 30 2e 31 31 31 33 36 32 0a 
-          3c 70 61 72 61 6d 65 74 65 72 3e 20 6f 73 63 31 
-          5f 77 61 76 65 66 6f 72 6d 20 31 0a 3c 70 61 72 
-          61 6d 65 74 65 72 3e 20 66 69 6c 74 65 72 5f 61 
-          74 74 61 63 6b 20 36 2e 39 35 36 38 38 65 2d 30 
-          39 0a 3c 70 61 72 61 6d 65 74 65 72 3e 20 66 69 
-          6c 74 65 72 5f 64 65 63 61 79 20 31 2e 31 30 30 
-          36 0a 3c 70 61 72 61 6d 65 74 65 72 3e 20 66 69 
-          6c 74 65 72 5f 73 75 73 74 61 69 6e 20 30 2e 32 
-          33 32 38 38 36 0a 3c 70 61 72 61 6d 65 74 65 72 
-          3e 20 66 69 6c 74 65 72 5f 72 65 6c 65 61 73 65 
-          20 30 2e 33 33 30 36 34 0a 3c 70 61 72 61 6d 65 
-          74 65 72 3e 20 66 69 6c 74 65 72 5f 72 65 73 6f 
-          6e 61 6e 63 65 20 30 2e 39 31 37 31 31 34 0a 3c 
-          70 61 72 61 6d 65 74 65 72 3e 20 66 69 6c 74 65 
-          72 5f 65 6e 76 5f 61 6d 6f 75 6e 74 20 31 30 2e 
-          35 39 33 34 0a 3c 70 61 72 61 6d 65 74 65 72 3e 
-          20 66 69 6c 74 65 72 5f 63 75 74 6f 66 66 20 2d 
-          30 2e 33 35 38 30 37 38 0a 3c 70 61 72 61 6d 65 
-          74 65 72 3e 20 6f 73 63 32 5f 64 65 74 75 6e 65 
-          20 30 0a 3c 70 61 72 61 6d 65 74 65 72 3e 20 6f 
-          73 63 32 5f 77 61 76 65 66 6f 72 6d 20 31 0a 3c 
-          70 61 72 61 6d 65 74 65 72 3e 20 6d 61 73 74 65 
-          72 5f 76 6f 6c 20 30 2e 35 32 32 39 0a 3c 70 61 
-          72 61 6d 65 74 65 72 3e 20 6c 66 6f 5f 66 72 65 
-          71 20 30 2e 38 30 38 32 30 34 0a 3c 70 61 72 61 
-          6d 65 74 65 72 3e 20 6c 66 6f 5f 77 61 76 65 66 
-          6f 72 6d 20 30 0a 3c 70 61 72 61 6d 65 74 65 72 
-          3e 20 6f 73 63 32 5f 72 61 6e 67 65 20 2d 31 0a 
-          3c 70 61 72 61 6d 65 74 65 72 3e 20 6f 73 63 5f 
-          6d 69 78 20 30 2e 32 30 31 37 31 0a 3c 70 61 72 
-          61 6d 65 74 65 72 3e 20 66 72 65 71 5f 6d 6f 64 
-          5f 61 6d 6f 75 6e 74 20 30 2e 32 35 31 39 38 34 
-          0a 3c 70 61 72 61 6d 65 74 65 72 3e 20 66 69 6c 
-          74 65 72 5f 6d 6f 64 5f 61 6d 6f 75 6e 74 20 2d 
-          30 2e 32 32 38 35 37 39 0a 3c 70 61 72 61 6d 65 
-          74 65 72 3e 20 61 6d 70 5f 6d 6f 64 5f 61 6d 6f 
-          75 6e 74 20 2d 30 2e 34 31 36 38 33 37 0a 3c 70 
-          61 72 61 6d 65 74 65 72 3e 20 6f 73 63 5f 6d 69 
-          78 5f 6d 6f 64 65 20 30 0a 3c 70 61 72 61 6d 65 
-          74 65 72 3e 20 6f 73 63 31 5f 70 75 6c 73 65 77 
-          69 64 74 68 20 30 2e 32 38 37 37 35 32 0a 3c 70 
-          61 72 61 6d 65 74 65 72 3e 20 6f 73 63 32 5f 70 
-          75 6c 73 65 77 69 64 74 68 20 30 2e 35 39 39 31 
-          35 0a 3c 70 61 72 61 6d 65 74 65 72 3e 20 72 65 
-          76 65 72 62 5f 72 6f 6f 6d 73 69 7a 65 20 30 2e 
-          33 33 39 39 35 37 0a 3c 70 61 72 61 6d 65 74 65 
-          72 3e 20 72 65 76 65 72 62 5f 64 61 6d 70 20 30 
-          2e 31 37 37 31 39 31 0a 3c 70 61 72 61 6d 65 74 
-          65 72 3e 20 72 65 76 65 72 62 5f 77 65 74 20 30 
-          2e 33 32 39 39 37 0a 3c 70 61 72 61 6d 65 74 65 
-          72 3e 20 72 65 76 65 72 62 5f 77 69 64 74 68 20 
-          30 2e 39 37 39 39 30 39 0a 3c 70 61 72 61 6d 65 
-          74 65 72 3e 20 64 69 73 74 6f 72 74 69 6f 6e 5f 
-          63 72 75 6e 63 68 20 32 2e 35 30 34 34 38 65 2d 
-          30 39 0a 3c 70 61 72 61 6d 65 74 65 72 3e 20 6f 
-          73 63 32 5f 73 79 6e 63 20 31 0a 3c 70 61 72 61 
-          6d 65 74 65 72 3e 20 70 6f 72 74 61 6d 65 6e 74 
-          6f 5f 74 69 6d 65 20 30 0a 3c 70 61 72 61 6d 65 
-          74 65 72 3e 20 6b 65 79 62 6f 61 72 64 5f 6d 6f 
-          64 65 20 30 0a 3c 70 61 72 61 6d 65 74 65 72 3e 
-          20 6f 73 63 32 5f 70 69 74 63 68 20 30 0a 3c 70 
-          61 72 61 6d 65 74 65 72 3e 20 66 69 6c 74 65 72 
-          5f 74 79 70 65 20 30 0a 3c 70 61 72 61 6d 65 74 
-          65 72 3e 20 66 69 6c 74 65 72 5f 73 6c 6f 70 65 
-          20 31 0a 3c 70 61 72 61 6d 65 74 65 72 3e 20 66 
-          72 65 71 5f 6d 6f 64 5f 6f 73 63 20 30 0a 3c 70 
-          61 72 61 6d 65 74 65 72 3e 20 66 69 6c 74 65 72 
-          5f 6b 62 64 5f 74 72 61 63 6b 20 31 0a 3c 70 61 
-          72 61 6d 65 74 65 72 3e 20 66 69 6c 74 65 72 5f 
-          76 65 6c 5f 73 65 6e 73 20 31 0a 3c 70 61 72 61 
-          6d 65 74 65 72 3e 20 61 6d 70 5f 76 65 6c 5f 73 
-          65 6e 73 20 31 0a 3c 70 61 72 61 6d 65 74 65 72 
-          3e 20 70 6f 72 74 61 6d 65 6e 74 6f 5f 6d 6f 64 
-          65 20 30 0a 
-          </event>
-        </midistate>
+      <customData>
+AAAFOnicdVRRrpswEPzvKbhAkG0wtqWnfPUGPYDlwNKggM2zDSk9fZfmpQ3gfIGY2d3ZYWwz/FhsvNKcjB4CxG8fj+c5+7BmgHP2HbwHm1EEjMcvEfw5M8OoTYymvmUkp/yANVCbBSFREqIOaJhCNJ
+1FnFHKGDsQPPRgAqy9KS2qLcGFmuq7maF1ftjparsen09pVa54JSWcdhq+WA+RNKeEVCn8RWbBpExy/istClKVaUpw1th6JSkqKE2ywM7aDG6yMaMk56pIsuopurbNTjiOSyLk3hiGS8XJ4qgj8say
+wYS18+x61McZ21rVt063Hj4Rk0QyUh7Qf20TI72xPyE70T2ih+7XaitBO7Zr4ig9uOZpBXI4VTLpxQsN/WBMcnGM2pZU0koWIqVmJSZco3qc+gD3ronXVYwUgh/SyLYkrtTuRHiYwV+0d24I3e9HWJ
+TiIkVqUPWaeyGooinCHVZbCqZUsv6pQgmldrFvuhCdj52zuvaTra8Zyzkpy+MB+btUWGy9y8qI5fhuo9OxG/Z+3WC5OOObN16iTV3EoST1M+My7kuep7B3CL2JCbZNV90ujY5+vQSSF8QMvQ5gQ+Ja
+ewO9rP613h8dyMZT</customData>
       <param>0.06</param>
       <param>0.296036</param>
       <param>0.211222</param>
```
